UPLOAD_FOLDER = 'uploads'
DEBUG = True
JSON_AS_ASCII = False
# SALT八位
SALT = 'AAAAAAAA'
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_USRT = 'root'
MYSQL_PASSWD = 'Wsz960402'
MYSQL_DB = 'student_db'